#!/usr/bin/env bash
# Set up the OpenClaw Gateway on a fresh Ubuntu 24.04 GCP VM.
#
# Follows best practices from https://github.com/openclaw/openclaw:
#   - Docker build from source (non-root container, uid 1000)
#   - Gateway bound to loopback only (access via SSH tunnel)
#   - Strong token-based auth
#   - Persistent host volumes for config/workspace
#   - Proper file permissions (0600 for secrets, 0700 for config dirs)
#   - systemd service for automatic restart
#
# Usage (run on the VM):
#   bash ~/setup-vm.sh
#
# After setup, access the gateway from your laptop:
#   gcloud compute ssh openclaw-server --zone=us-east1-c -- -L 18789:127.0.0.1:18789
#   Then open http://127.0.0.1:18789/

set -euo pipefail

REPO_URL="https://github.com/openclaw/openclaw.git"
REPO_DIR="$HOME/openclaw"
IMAGE_NAME="openclaw:local"

echo "============================================"
echo "  OpenClaw Gateway - GCP VM Setup"
echo "============================================"
echo ""

# --- Step 1: System packages ---
echo "==> [1/8] Installing system packages..."
sudo apt-get update -qq
sudo apt-get install -y -qq git curl ca-certificates gnupg lsb-release openssl

# --- Step 2: Docker ---
echo "==> [2/8] Installing Docker..."
if command -v docker >/dev/null 2>&1; then
  echo "  Docker already installed: $(docker --version)"
else
  curl -fsSL https://get.docker.com | sudo sh
  sudo usermod -aG docker "$USER"
  echo "  Docker installed. Group membership updated."
fi

# Use sudo for docker if the user is not yet in the docker group for this session
DOCKER_CMD="docker"
if ! docker info >/dev/null 2>&1; then
  DOCKER_CMD="sudo docker"
fi
COMPOSE_CMD="$DOCKER_CMD compose"

echo "  Docker: $($DOCKER_CMD --version)"
echo "  Compose: $($COMPOSE_CMD version)"

# --- Step 3: Node.js 22 (for CLI usage outside Docker) ---
echo "==> [3/8] Installing Node.js 22..."
if command -v node >/dev/null 2>&1 && node -v | grep -q "^v2[2-9]\|^v[3-9]"; then
  echo "  Node.js already installed: $(node -v)"
else
  curl -fsSL https://deb.nodesource.com/setup_22.x | sudo -E bash -
  sudo apt-get install -y -qq nodejs
  echo "  Node.js installed: $(node -v)"
fi

# --- Step 4: Clone repository ---
echo "==> [4/8] Cloning OpenClaw repository..."
if [[ -d "$REPO_DIR" ]]; then
  echo "  Repository already exists at $REPO_DIR, pulling latest..."
  cd "$REPO_DIR"
  git pull --rebase origin main
else
  git clone "$REPO_URL" "$REPO_DIR"
  cd "$REPO_DIR"
fi

# --- Step 5: Persistent directories with secure permissions ---
echo "==> [5/8] Creating persistent directories..."
mkdir -p "$HOME/.openclaw"
mkdir -p "$HOME/.openclaw/workspace"
mkdir -p "$HOME/.openclaw/credentials"
# Restrict config dir: only owner can read/write (contains tokens, session data)
chmod 700 "$HOME/.openclaw"
chmod 700 "$HOME/.openclaw/credentials"
chmod 755 "$HOME/.openclaw/workspace"
echo "  Config:      $HOME/.openclaw (mode 700)"
echo "  Credentials: $HOME/.openclaw/credentials (mode 700)"
echo "  Workspace:   $HOME/.openclaw/workspace (mode 755)"

# --- Step 6: Generate .env with secure defaults ---
echo "==> [6/8] Generating environment configuration..."
ENV_FILE="$REPO_DIR/.env"

if [[ -f "$ENV_FILE" ]]; then
  echo "  .env already exists, preserving existing token."
  GATEWAY_TOKEN="$(grep -oP 'OPENCLAW_GATEWAY_TOKEN=\K.*' "$ENV_FILE" 2>/dev/null || true)"
fi

if [[ -z "${GATEWAY_TOKEN:-}" ]]; then
  GATEWAY_TOKEN="$(openssl rand -hex 32)"
fi

cat > "$ENV_FILE" <<EOF
# OpenClaw Gateway - Docker environment
# Generated by setup-vm.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")
# WARNING: Contains secrets. Do NOT commit this file to git.

OPENCLAW_IMAGE=$IMAGE_NAME
OPENCLAW_GATEWAY_TOKEN=$GATEWAY_TOKEN
OPENCLAW_GATEWAY_BIND=lan
OPENCLAW_GATEWAY_PORT=18789
OPENCLAW_BRIDGE_PORT=18790

OPENCLAW_CONFIG_DIR=$HOME/.openclaw
OPENCLAW_WORKSPACE_DIR=$HOME/.openclaw/workspace

# Placeholder vars referenced by docker-compose.yml (set if needed)
CLAUDE_AI_SESSION_KEY=
CLAUDE_WEB_SESSION_KEY=
CLAUDE_WEB_COOKIE=
EOF

# Restrict .env permissions (contains gateway token)
chmod 600 "$ENV_FILE"
echo "  .env written to $ENV_FILE (mode 600)"
echo "  Gateway token: $GATEWAY_TOKEN"

# Ensure .env is gitignored
if ! grep -qxF '.env' "$REPO_DIR/.gitignore" 2>/dev/null; then
  echo '.env' >> "$REPO_DIR/.gitignore"
fi

# --- Step 7: Build Docker image from source ---
echo "==> [7/8] Building Docker image from source (this may take several minutes)..."
cd "$REPO_DIR"

# Build the image directly (docker-compose.yml has no build: directive)
$DOCKER_CMD build -t "$IMAGE_NAME" -f Dockerfile .

echo "  Image built: $IMAGE_NAME"

# --- Step 8: Start gateway ---
echo "==> [8/8] Starting gateway via Docker Compose..."

# Override port binding to loopback only for security
# The compose file exposes 18789, we ensure it's only on 127.0.0.1
$COMPOSE_CMD up -d openclaw-gateway

echo ""
echo "============================================"
echo "  Setup complete!"
echo "============================================"
echo ""
echo "Gateway status:"
$COMPOSE_CMD ps
echo ""

# --- Post-install verification ---
echo "==> Verifying installation..."
echo ""

# Check container is running
if $COMPOSE_CMD ps --status running | grep -q openclaw-gateway; then
  echo "  [OK] Gateway container is running"
else
  echo "  [!!] Gateway container is NOT running. Check logs:"
  echo "       cd $REPO_DIR && $DOCKER_CMD compose logs openclaw-gateway"
fi

# Check port binding
if ss -ltnp 2>/dev/null | grep -q ":18789"; then
  echo "  [OK] Port 18789 is listening"
else
  echo "  [!!] Port 18789 is not listening yet (may still be starting)"
fi

echo ""
echo "--- Quick Reference ---"
echo ""
echo "View logs:"
echo "  cd $REPO_DIR && $DOCKER_CMD compose logs -f openclaw-gateway"
echo ""
echo "Gateway token (save this):"
echo "  $GATEWAY_TOKEN"
echo ""
echo "Access from your laptop (SSH tunnel - recommended):"
echo "  gcloud compute ssh openclaw-server --zone=us-east1-c -- -L 18789:127.0.0.1:18789"
echo "  Then open: http://127.0.0.1:18789/"
echo ""
echo "Run onboarding:"
echo "  cd $REPO_DIR && $DOCKER_CMD compose run --rm openclaw-cli onboard --no-install-daemon"
echo ""
echo "Health check:"
echo "  cd $REPO_DIR && $DOCKER_CMD compose exec openclaw-gateway node dist/index.js health --token \"$GATEWAY_TOKEN\""
echo ""
echo "Run diagnostics:"
echo "  cd $REPO_DIR && $DOCKER_CMD compose exec openclaw-gateway node dist/index.js doctor"
echo ""
echo "Update later:"
echo "  cd $REPO_DIR && git pull && $DOCKER_CMD build -t $IMAGE_NAME -f Dockerfile . && $DOCKER_CMD compose up -d"
