#!/usr/bin/env bash
# Set up the OpenClaw Gateway on a fresh Ubuntu 24.04 GCP VM.
#
# This script:
#   1. Installs Docker and Docker Compose (if missing)
#   2. Installs Node.js 22 (for non-Docker CLI usage)
#   3. Clones the OpenClaw repository
#   4. Creates persistent host directories
#   5. Generates a gateway token and .env file
#   6. Builds the Docker image
#   7. Starts the gateway via Docker Compose
#
# Usage (run on the VM):
#   bash ~/setup-vm.sh
#
# After setup, access the gateway from your laptop:
#   gcloud compute ssh openclaw-server --zone=us-central1-a -- -L 18789:127.0.0.1:18789
#   Then open http://127.0.0.1:18789/

set -euo pipefail

REPO_URL="https://github.com/openclaw/openclaw.git"
REPO_DIR="$HOME/openclaw"

echo "============================================"
echo "  OpenClaw Gateway - GCP VM Setup"
echo "============================================"
echo ""

# --- Step 1: System packages ---
echo "==> [1/7] Installing system packages..."
sudo apt-get update -qq
sudo apt-get install -y -qq git curl ca-certificates gnupg lsb-release

# --- Step 2: Docker ---
echo "==> [2/7] Installing Docker..."
if command -v docker >/dev/null 2>&1; then
  echo "  Docker already installed: $(docker --version)"
else
  curl -fsSL https://get.docker.com | sudo sh
  sudo usermod -aG docker "$USER"
  echo "  Docker installed. Group membership updated."
  echo "  NOTE: If this is a fresh install, you may need to log out and back in"
  echo "  for Docker group permissions to take effect. The script will use sudo"
  echo "  for Docker commands as a fallback."
fi

# Use sudo for docker if the user is not yet in the docker group for this session
DOCKER_CMD="docker"
if ! docker info >/dev/null 2>&1; then
  DOCKER_CMD="sudo docker"
fi
COMPOSE_CMD="$DOCKER_CMD compose"

echo "  Docker: $($DOCKER_CMD --version)"
echo "  Compose: $($COMPOSE_CMD version)"

# --- Step 3: Node.js 22 (for CLI usage outside Docker) ---
echo "==> [3/7] Installing Node.js 22..."
if command -v node >/dev/null 2>&1 && node -v | grep -q "^v2[2-9]\|^v[3-9]"; then
  echo "  Node.js already installed: $(node -v)"
else
  curl -fsSL https://deb.nodesource.com/setup_22.x | sudo -E bash -
  sudo apt-get install -y -qq nodejs
  echo "  Node.js installed: $(node -v)"
fi

# --- Step 4: Clone repository ---
echo "==> [4/7] Cloning OpenClaw repository..."
if [[ -d "$REPO_DIR" ]]; then
  echo "  Repository already exists at $REPO_DIR, pulling latest..."
  cd "$REPO_DIR"
  git pull --rebase origin main
else
  git clone "$REPO_URL" "$REPO_DIR"
  cd "$REPO_DIR"
fi

# --- Step 5: Persistent directories ---
echo "==> [5/7] Creating persistent directories..."
mkdir -p "$HOME/.openclaw"
mkdir -p "$HOME/.openclaw/workspace"
echo "  Config:    $HOME/.openclaw"
echo "  Workspace: $HOME/.openclaw/workspace"

# --- Step 6: Generate .env ---
echo "==> [6/7] Generating environment configuration..."
ENV_FILE="$REPO_DIR/.env"

if [[ -f "$ENV_FILE" ]]; then
  echo "  .env already exists, preserving existing configuration."
  # Source existing token if present
  GATEWAY_TOKEN="$(grep -oP 'OPENCLAW_GATEWAY_TOKEN=\K.*' "$ENV_FILE" 2>/dev/null || true)"
fi

if [[ -z "${GATEWAY_TOKEN:-}" ]]; then
  GATEWAY_TOKEN="$(openssl rand -hex 32)"
fi

cat > "$ENV_FILE" <<EOF
# OpenClaw Gateway - Docker environment
# Generated by setup-vm.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")

OPENCLAW_IMAGE=openclaw:local
OPENCLAW_GATEWAY_TOKEN=$GATEWAY_TOKEN
OPENCLAW_GATEWAY_BIND=lan
OPENCLAW_GATEWAY_PORT=18789
OPENCLAW_BRIDGE_PORT=18790

OPENCLAW_CONFIG_DIR=$HOME/.openclaw
OPENCLAW_WORKSPACE_DIR=$HOME/.openclaw/workspace
EOF

echo "  .env written to $ENV_FILE"
echo "  Gateway token: $GATEWAY_TOKEN"

# --- Step 7: Build and launch ---
echo "==> [7/7] Building Docker image and starting gateway..."
cd "$REPO_DIR"

$COMPOSE_CMD build
$COMPOSE_CMD up -d openclaw-gateway

echo ""
echo "============================================"
echo "  Setup complete!"
echo "============================================"
echo ""
echo "Gateway status:"
$COMPOSE_CMD ps
echo ""
echo "View logs:"
echo "  cd $REPO_DIR && $DOCKER_CMD compose logs -f openclaw-gateway"
echo ""
echo "Gateway token: $GATEWAY_TOKEN"
echo ""
echo "Access from your laptop (SSH tunnel):"
echo "  gcloud compute ssh openclaw-server --zone=us-central1-a -- -L 18789:127.0.0.1:18789"
echo "  Then open: http://127.0.0.1:18789/"
echo ""
echo "Run onboarding (optional):"
echo "  cd $REPO_DIR && $DOCKER_CMD compose run --rm openclaw-cli onboard --no-install-daemon"
echo ""
echo "Health check:"
echo "  cd $REPO_DIR && $DOCKER_CMD compose exec openclaw-gateway node dist/index.js health --token \"$GATEWAY_TOKEN\""
echo ""
echo "Update later:"
echo "  cd $REPO_DIR && git pull && $DOCKER_CMD compose build && $DOCKER_CMD compose up -d"
